### PR TITLE
replaced null pointers with nullptr

### PR DESCRIPTION
**Pull request by mahrud**

### CODE REVIEW

**Comment by mikestillman** [comment]
@mahrud @d-torrance I just merged this mathicgb pull request.  Would one of you create a M2 pull request to match this?

**Comment by mikestillman** [comment]
Actually, we might need to make one other change to mathicgb first (I have a change that is required to run under c++20, which although we are at c++17, it is nice to experiment with).

**Comment by mikestillman** [comment]
Here is the change to be made:
```
diff --git a/src/mathicgb/mtbb.hpp b/src/mathicgb/mtbb.hpp
index c14cd9d..7bb8bd2 100644
--- a/src/mathicgb/mtbb.hpp
+++ b/src/mathicgb/mtbb.hpp
@@ -23,6 +23,7 @@
 #include <mutex>
 
 namespace mtbb {
+  using ::tbb::global_control;
   using ::tbb::task_arena;
   using ::tbb::enumerable_thread_specific;
   using ::tbb::queuing_mutex;
diff --git a/src/test/poly-test.cpp b/src/test/poly-test.cpp
index 65cf106..3c99beb 100644
--- a/src/test/poly-test.cpp
+++ b/src/test/poly-test.cpp
@@ -629,7 +629,8 @@ TEST(Poly,lead) {
   const auto& monoid = R->monoid();
   monomial lm = stringToMonomial(R.get(), "ab");
   EXPECT_TRUE(monoid.equal(lm, I->getPoly(0)->leadMono()));
-  EXPECT_EQ(1, I->getPoly(0)->leadCoef());
+  auto val = I->getPoly(0)->leadCoef();
+  EXPECT_EQ(static_cast<decltype(val)>(1), val);
   EXPECT_EQ(0, monoid.component(I->getPoly(0)->leadMono()));
   R->freeMonomial(lm);
 }
```

**Comment by mahrud** [comment]
Hmm it looks like merging changed the commit, even though it should have simply fast-forwarded. Maybe I don't understand how GitHub handles this.

Either way, we can wait until your c++20 changes are there.

**Comment by mikestillman** [comment]
OK, I checked in the change, forgot to make it a pull request and just pushed it.  It seems to be commit 4cd2bd13571.

@mahrud I think that doing rebasing+merge, it needs to create a new commit node.

**Comment by mahrud** [comment]
At least locally, rebase doesn't create new commit nodes if it can be fast-forwarded. I'll look into what GitHub does.

**Comment by d-torrance** [comment]
I just opened https://github.com/Macaulay2/M2/pull/3110 updating the mathicgb submodule in the main M2 repository (including this most recent C++20 commit)

**Comment by mikestillman** [comment]
@d-torrance Thanks, if it passes tests, I'll accept it in the morning.

**Pull request merged**
