### PR TITLE
Remove executable bit on several example files.

### PR DESCRIPTION
**Pull request by d-torrance**

### CODE REVIEW

**Comment by mikestillman** [comment]
@d-torrance You have 3 open pull requests on macaulay2/mathicgb.  Are these all valid still?

**Comment by d-torrance** [comment]
This one and #10 are still valid.

The issue that prompted #15 is still valid, but the proposed fix could be improved to make it more like the check that ultimately made it into Macaulay2 (https://github.com/Macaulay2/M2/commit/9f7368a).  I'll work on adapting that soon.

**Comment by mahrud** [comment]
This should be fixed in the CMake PR I believe, specifically in 0f12b79dab14ebe3b40858a545d6e7ead3ac45b7. I wonder why it's not giving a conflict.

**Comment by d-torrance** [comment]
Indeed it is!  Closing.

**Pull request closed without merging**
